### ISSUE TITLE
Free rooms API adjustments

### ISSUE THREAD

**Issue by mininao** [BDE-ESIEE/API-calendar#3]
Do you think we should adjust the api in `/app/roomfinder/index.js` to give a more "human interpretable" output, eg don't include rooms that will be unavailable in 5 minutes

**Comment by mininao** [comment]
Let's put the safeguard delta in the config #10
And i feel the safeguard should also apply to rooms that _will_ be available in 5 minutes

**Comment by minijackson** [comment]
I don't think that's a good idea to give rooms that will be available in the future
